# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/work/osCOMP/proj166-gmssl-on-freertos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/work/osCOMP/proj166-gmssl-on-freertos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/work/osCOMP/proj166-gmssl-on-freertos/CMakeFiles /mnt/d/work/osCOMP/proj166-gmssl-on-freertos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/work/osCOMP/proj166-gmssl-on-freertos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sm4test

# Build rule for target.
sm4test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sm4test
.PHONY : sm4test

# fast build rule for target.
sm4test/fast:
	$(MAKE) -f CMakeFiles/sm4test.dir/build.make CMakeFiles/sm4test.dir/build
.PHONY : sm4test/fast

#=============================================================================
# Target rules for targets named gmssl

# Build rule for target.
gmssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmssl
.PHONY : gmssl

# fast build rule for target.
gmssl/fast:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/build
.PHONY : gmssl/fast

src/aes.o: src/aes.c.o

.PHONY : src/aes.o

# target to build an object file
src/aes.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/aes.c.o
.PHONY : src/aes.c.o

src/aes.i: src/aes.c.i

.PHONY : src/aes.i

# target to preprocess a source file
src/aes.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/aes.c.i
.PHONY : src/aes.c.i

src/aes.s: src/aes.c.s

.PHONY : src/aes.s

# target to generate assembly for a file
src/aes.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/aes.c.s
.PHONY : src/aes.c.s

src/aes_modes.o: src/aes_modes.c.o

.PHONY : src/aes_modes.o

# target to build an object file
src/aes_modes.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/aes_modes.c.o
.PHONY : src/aes_modes.c.o

src/aes_modes.i: src/aes_modes.c.i

.PHONY : src/aes_modes.i

# target to preprocess a source file
src/aes_modes.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/aes_modes.c.i
.PHONY : src/aes_modes.c.i

src/aes_modes.s: src/aes_modes.c.s

.PHONY : src/aes_modes.s

# target to generate assembly for a file
src/aes_modes.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/aes_modes.c.s
.PHONY : src/aes_modes.c.s

src/block_cipher.o: src/block_cipher.c.o

.PHONY : src/block_cipher.o

# target to build an object file
src/block_cipher.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/block_cipher.c.o
.PHONY : src/block_cipher.c.o

src/block_cipher.i: src/block_cipher.c.i

.PHONY : src/block_cipher.i

# target to preprocess a source file
src/block_cipher.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/block_cipher.c.i
.PHONY : src/block_cipher.c.i

src/block_cipher.s: src/block_cipher.c.s

.PHONY : src/block_cipher.s

# target to generate assembly for a file
src/block_cipher.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/block_cipher.c.s
.PHONY : src/block_cipher.c.s

src/gcm.o: src/gcm.c.o

.PHONY : src/gcm.o

# target to build an object file
src/gcm.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/gcm.c.o
.PHONY : src/gcm.c.o

src/gcm.i: src/gcm.c.i

.PHONY : src/gcm.i

# target to preprocess a source file
src/gcm.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/gcm.c.i
.PHONY : src/gcm.c.i

src/gcm.s: src/gcm.c.s

.PHONY : src/gcm.s

# target to generate assembly for a file
src/gcm.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/gcm.c.s
.PHONY : src/gcm.c.s

src/gf128.o: src/gf128.c.o

.PHONY : src/gf128.o

# target to build an object file
src/gf128.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/gf128.c.o
.PHONY : src/gf128.c.o

src/gf128.i: src/gf128.c.i

.PHONY : src/gf128.i

# target to preprocess a source file
src/gf128.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/gf128.c.i
.PHONY : src/gf128.c.i

src/gf128.s: src/gf128.c.s

.PHONY : src/gf128.s

# target to generate assembly for a file
src/gf128.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/gf128.c.s
.PHONY : src/gf128.c.s

src/rand.o: src/rand.c.o

.PHONY : src/rand.o

# target to build an object file
src/rand.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/rand.c.o
.PHONY : src/rand.c.o

src/rand.i: src/rand.c.i

.PHONY : src/rand.i

# target to preprocess a source file
src/rand.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/rand.c.i
.PHONY : src/rand.c.i

src/rand.s: src/rand.c.s

.PHONY : src/rand.s

# target to generate assembly for a file
src/rand.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/rand.c.s
.PHONY : src/rand.c.s

src/sm3.o: src/sm3.c.o

.PHONY : src/sm3.o

# target to build an object file
src/sm3.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm3.c.o
.PHONY : src/sm3.c.o

src/sm3.i: src/sm3.c.i

.PHONY : src/sm3.i

# target to preprocess a source file
src/sm3.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm3.c.i
.PHONY : src/sm3.c.i

src/sm3.s: src/sm3.c.s

.PHONY : src/sm3.s

# target to generate assembly for a file
src/sm3.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm3.c.s
.PHONY : src/sm3.c.s

src/sm4_common.o: src/sm4_common.c.o

.PHONY : src/sm4_common.o

# target to build an object file
src/sm4_common.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_common.c.o
.PHONY : src/sm4_common.c.o

src/sm4_common.i: src/sm4_common.c.i

.PHONY : src/sm4_common.i

# target to preprocess a source file
src/sm4_common.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_common.c.i
.PHONY : src/sm4_common.c.i

src/sm4_common.s: src/sm4_common.c.s

.PHONY : src/sm4_common.s

# target to generate assembly for a file
src/sm4_common.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_common.c.s
.PHONY : src/sm4_common.c.s

src/sm4_enc.o: src/sm4_enc.c.o

.PHONY : src/sm4_enc.o

# target to build an object file
src/sm4_enc.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_enc.c.o
.PHONY : src/sm4_enc.c.o

src/sm4_enc.i: src/sm4_enc.c.i

.PHONY : src/sm4_enc.i

# target to preprocess a source file
src/sm4_enc.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_enc.c.i
.PHONY : src/sm4_enc.c.i

src/sm4_enc.s: src/sm4_enc.c.s

.PHONY : src/sm4_enc.s

# target to generate assembly for a file
src/sm4_enc.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_enc.c.s
.PHONY : src/sm4_enc.c.s

src/sm4_modes.o: src/sm4_modes.c.o

.PHONY : src/sm4_modes.o

# target to build an object file
src/sm4_modes.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_modes.c.o
.PHONY : src/sm4_modes.c.o

src/sm4_modes.i: src/sm4_modes.c.i

.PHONY : src/sm4_modes.i

# target to preprocess a source file
src/sm4_modes.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_modes.c.i
.PHONY : src/sm4_modes.c.i

src/sm4_modes.s: src/sm4_modes.c.s

.PHONY : src/sm4_modes.s

# target to generate assembly for a file
src/sm4_modes.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_modes.c.s
.PHONY : src/sm4_modes.c.s

src/sm4_setkey.o: src/sm4_setkey.c.o

.PHONY : src/sm4_setkey.o

# target to build an object file
src/sm4_setkey.c.o:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_setkey.c.o
.PHONY : src/sm4_setkey.c.o

src/sm4_setkey.i: src/sm4_setkey.c.i

.PHONY : src/sm4_setkey.i

# target to preprocess a source file
src/sm4_setkey.c.i:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_setkey.c.i
.PHONY : src/sm4_setkey.c.i

src/sm4_setkey.s: src/sm4_setkey.c.s

.PHONY : src/sm4_setkey.s

# target to generate assembly for a file
src/sm4_setkey.c.s:
	$(MAKE) -f CMakeFiles/gmssl.dir/build.make CMakeFiles/gmssl.dir/src/sm4_setkey.c.s
.PHONY : src/sm4_setkey.c.s

test/sm4test.o: test/sm4test.c.o

.PHONY : test/sm4test.o

# target to build an object file
test/sm4test.c.o:
	$(MAKE) -f CMakeFiles/sm4test.dir/build.make CMakeFiles/sm4test.dir/test/sm4test.c.o
.PHONY : test/sm4test.c.o

test/sm4test.i: test/sm4test.c.i

.PHONY : test/sm4test.i

# target to preprocess a source file
test/sm4test.c.i:
	$(MAKE) -f CMakeFiles/sm4test.dir/build.make CMakeFiles/sm4test.dir/test/sm4test.c.i
.PHONY : test/sm4test.c.i

test/sm4test.s: test/sm4test.c.s

.PHONY : test/sm4test.s

# target to generate assembly for a file
test/sm4test.c.s:
	$(MAKE) -f CMakeFiles/sm4test.dir/build.make CMakeFiles/sm4test.dir/test/sm4test.c.s
.PHONY : test/sm4test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... sm4test"
	@echo "... gmssl"
	@echo "... src/aes.o"
	@echo "... src/aes.i"
	@echo "... src/aes.s"
	@echo "... src/aes_modes.o"
	@echo "... src/aes_modes.i"
	@echo "... src/aes_modes.s"
	@echo "... src/block_cipher.o"
	@echo "... src/block_cipher.i"
	@echo "... src/block_cipher.s"
	@echo "... src/gcm.o"
	@echo "... src/gcm.i"
	@echo "... src/gcm.s"
	@echo "... src/gf128.o"
	@echo "... src/gf128.i"
	@echo "... src/gf128.s"
	@echo "... src/rand.o"
	@echo "... src/rand.i"
	@echo "... src/rand.s"
	@echo "... src/sm3.o"
	@echo "... src/sm3.i"
	@echo "... src/sm3.s"
	@echo "... src/sm4_common.o"
	@echo "... src/sm4_common.i"
	@echo "... src/sm4_common.s"
	@echo "... src/sm4_enc.o"
	@echo "... src/sm4_enc.i"
	@echo "... src/sm4_enc.s"
	@echo "... src/sm4_modes.o"
	@echo "... src/sm4_modes.i"
	@echo "... src/sm4_modes.s"
	@echo "... src/sm4_setkey.o"
	@echo "... src/sm4_setkey.i"
	@echo "... src/sm4_setkey.s"
	@echo "... test/sm4test.o"
	@echo "... test/sm4test.i"
	@echo "... test/sm4test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

